In [2]:
import numpy as np

In [4]:
array_1 = np.arange(10).reshape((5,2))
array_1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [5]:
# Add 1 to every element of the array by broadcasting

array_1 + 1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [7]:
# Create a new array_2 array. Multiply it by itself.

array_2 = np.arange(10)
array_2 * array_2            #element-wise multipliaction of arrays

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [8]:
# Another example

array_2 = array_2**2    #equivalent to array_2 * array_2
array_2
array_2 = array_2.reshape((5,2))
array_2

array([[ 0,  1],
       [ 4,  9],
       [16, 25],
       [36, 49],
       [64, 81]], dtype=int32)

In [10]:
# Change array_1 as well

array_1 = array_1 + 1
array_1

array([[ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [11]:
# Now add array_1 and array_2 element wise

array_1 + array_2

array([[ 2,  4],
       [ 8, 14],
       [22, 32],
       [44, 58],
       [74, 92]])

The formal broadcasting rule require that whenever you are comparing the shapes of both arrays from
left to right, all the numbers have to either match or be one.