## Initialize NumPy arrays and dtypes

In [1]:
import numpy as np

In [4]:
# Initialize a numpy array of zeros

np.zeros((5,2))         #array of zeros with shape (5,2)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [5]:
# Initialize an array of ones. Use a dtype argument to insure the array elements are of INT type

np.ones((5,2), dtype = np.int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [6]:
# Create an uninitialized array of specific size and dtype and allocate memory

np.empty((5,2), dtype = np.float)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

## Indexing

In [10]:
# Look up the values of the two dimensional arrays with indexing

array_1 = np.arange(10).reshape((5,2))
array_1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [11]:
 # first row and first column

array_1[0,0]                          

0

In [13]:
# View the first row

array_1[0,:]

array([0, 1])

In [15]:
# View the first column

array_1[:,0]

array([0, 2, 4, 6, 8])

In [18]:
# View second to fourth rows

array_1[1:4,:]

array([[2, 3],
       [4, 5],
       [6, 7]])

In [19]:
# View the second to the fourth rows only along the first column

array_1[1:4,0]

array([2, 4, 6])

## Boolean Arrays

In [21]:
# Produce a boolean array

array_1 > 5

array([[False, False],
       [False, False],
       [False, False],
       [ True,  True],
       [ True,  True]])

In [22]:
# Filter by the boolean array

array_1[array_1 > 5]

array([6, 7, 8, 9])

## Arithmetic Operations

In [24]:
# Add all the elements of the array with the sum method

array_1.sum()

45

In [28]:
# Find all sums by row

array_1.sum(axis = 1)

array([ 1,  5,  9, 13, 17])

In [29]:
# Find all sums by column

array_1.sum(axis = 0)

array([20, 25])

In [31]:
# Find the mean of each column

array_1.mean(axis = 0)        #dtype is float

array([4., 5.])

## NaN values

In [32]:
array_3 = np.array([np.nan, 0, 1, 2, np.nan])

In [33]:
# Find the NaN values with a special boolean array

np.isnan(array_3)

array([ True, False, False, False,  True])

In [34]:
# Filter the nan values by negating the Boolean array with symbol ~

array_3[~np.isnan(array_3)]

array([0., 1., 2.])

In [36]:
# Set the nan values to zero

array_3[np.isnan(array_3)] = 0
array_3

array([0., 0., 1., 2., 0.])